// ReactApp/src/components/Footer.tsx
import React, { FC } from 'react';
import { Footer } from 'flowbite-react';

const FooterPage: FC = () => (
  <Footer container className="bg-gray-600 mt-8 rounded-none">
    <Footer.Copyright
      className="text-blue-50"
      href="/"
      by="Paweł Włodarczyk"
      year={2023}
    />
  </Footer>
);

export default FooterPage;

// VueApp/src/components/Footer.vue
<template>
  <footer class="p-4 bg-gray-600 mt-8 rounded-none shadow md:flex md:items-center md:justify-between md:p-6">
    <span class="text-sm text-white sm:text-center">© 2023 <span class="hover:underline">Paweł Włodarczyk</span>
    </span>
  </footer>
</template>

<script setup lang="ts">
</script>
