// ReactApp/src/components/NavBar.tsx
import React, { FC, useState } from 'react';
import { Button, Navbar } from 'flowbite-react';
import { useLocation } from 'react-router-dom';
import axios from 'axios';
import { toast } from 'react-toastify';
import Pathnames from '../consts/pathnames';
import LoginSignupModal from './LoginSignupModal';

interface Props {
  userToken: string | null
}
const NavBar: FC<Props> = ({ userToken }) => {
  const location = useLocation();
  const [showModal, setShowModal] = useState<boolean>(false);
  const [registered, setRegistered] = useState<boolean>(false);
  const email = localStorage.getItem('user');
  const checkLocation = (locationString: string, pathname: string) => locationString === pathname;
  const logout = async () => {
    const response = await axios.post(`${import.meta.env.VITE_HOST}/logout`, { email }, {
      withCredentials: true,
      headers: {
        'Access-Control-Allow-Credential': true,
      },
    });
    if (response.status !== 200) {
      toast.error('Could not logout');
      return;
    }
    setRegistered(false);
    localStorage.removeItem('token');
    document.location.reload();
  };
  return (
    <>
      <Navbar
        fluid
        className="bg-gray-600"
      >
        <Navbar.Brand>
          <span className="self-center whitespace-nowrap text-xl font-semibold text-white dark:text-white">
            MasterApp
          </span>
        </Navbar.Brand>
        <div className="flex md:order-2">
          {userToken ? (
            <>
              <p className="m-auto text-white">{email}</p>
              <Button onClick={() => logout()} className="ml-2">
                Logout
              </Button>
            </>
          ) : (
            <Button onClick={() => setShowModal(true)} className="mr-2">
              {registered ? 'Log in' : 'Sign In' }
            </Button>
          ) }
          <Navbar.Toggle />
        </div>
        <Navbar.Collapse>
          <Navbar.Link
            className="text-blue-50"
            href="/"
            active={checkLocation(location.pathname, Pathnames.HOME)}
          >
            Home
          </Navbar.Link>
          <Navbar.Link
            className="text-blue-50"
            href="/second"
            active={checkLocation(location.pathname, Pathnames.SECOND)}
          >
            Panel
          </Navbar.Link>
        </Navbar.Collapse>
      </Navbar>
      <LoginSignupModal
        onClose={() => setShowModal(false)}
        show={showModal}
        registered={registered}
        onRegister={setRegistered}
      />
    </>
  );
};
export default NavBar;

// VueApp/src/components/Navbar.vue
<template>
  <div>
    <Navbar>
      <template #logo>
        <NavbarLogo class="text-gray-700" link="/" image-url="https://masteringjs.io/assets/images/vue/vue.svg">
          MasterVueApp
        </NavbarLogo>
      </template>
      <template #default="{ isShowMenu }">
        <NavbarCollapse class="center-nav" :isShowMenu="isShowMenu">
          <NavbarLink class="text-nav" :is-active="props.isActive === 'Home'" link="/">Home</NavbarLink>
          <NavbarLink class="text-nav" :is-active="props.isActive === 'Panel'" link="/panel">Panel</NavbarLink>
        </NavbarCollapse>
        <div v-show="props.isLoggedOut">
          <button
            type="button"
            v-show="isSubmitted"
            @click="showModal"
            class="mt-2 ml-40 lg:ml-0 lg:mt-0 text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Log in
          </button>
          <button
            type="button"
            v-show="!isSubmitted"
            @click="showModal"
            class="mt-2 ml-40 lg:ml-0 lg:mt-0 text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Register Account
          </button>
        </div>
        <div class="xl:flex w-full xl:w-auto" v-show="!props.isLoggedOut">
          <p class="text-center mt-3 xl:mt-2 xl:ml-0 xl:mr-3 text-gray-700" v-text="email" />
          <div class="flex justify-center">
            <button
              type="button"
              @click="logout"
              class="mt-2 lg:ml-0 lg:mt-0 text-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
            >
              Logout
            </button>
          </div>
        </div>
      </template>
    </Navbar>
    <SignUpAndLogin
      :close-modal="closeModal"
      :show-modal="isShowModal"
      :is-submitted="isSubmitted"
      :set-submit="isSubmit"
      :delete-submit="deleteSubmit" />
  </div>
</template>

<script setup lang="ts">
import {
  Navbar, NavbarLogo, NavbarCollapse, NavbarLink,
} from 'flowbite-vue';
import { ref } from 'vue';
import { useToast } from 'vue-toastification';
import SignUpAndLogin from './SignUpAndLogin.vue';
import UserDataService from '../services/UserDataService';

const props = defineProps({
  isActive: { type: String, required: true },
  isLoggedOut: { type: Boolean, required: true },
  email: { type: String, default() { return ''; } },
});

const isShowModal = ref(false);
const isSubmitted = ref(false);

const toast = useToast();

const logout = () => {
  UserDataService.logout(props.email).then((res) => {
    if (res.status !== 200) {
      toast.error('Could not logout');
    } else {
      isSubmitted.value = false;
      localStorage.removeItem('token');
      localStorage.removeItem('email');
      document.location.reload();
    }
  });
};

function isSubmit() {
  isSubmitted.value = true;
}

function deleteSubmit() {
  isSubmitted.value = false;
}
function closeModal() {
  isShowModal.value = false;
}
function showModal() {
  isShowModal.value = true;
}

</script>
